project:
  type: book
  output-dir: docs
  
book:
  title: "Research-Bookdown"
  author: "Kyeong Sun Kim"
  date: "2023. 3. 12."
  chapters:
    - index.qmd
    - 01_practice_01.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

